[package]
name = "valve"
version = "0.1.0"
# Because of this issue: https://github.com/lalrpop/lalrpop/issues/650 we need to use the 2018
# edition of rust for now.
edition = "2018"
build = "build.rs"

[lib]
name = "valve"
crate-type = ["cdylib", "lib"]

[build-dependencies.lalrpop]
version = "0.19.7"
features = ["lexer"]

[dependencies]
async-std = { version = "1", features = [ "attributes" ] }
async-scoped = { version = "0.7.0", features = [ "use-async-std" ] }
crossbeam = "0.8.1"
csv = "1.1"
enquote = "1.1.0"
futures = "0.3"
itertools = "0.10.3"
lazy_static = "1.4.0"
num_cpus = "1.13.1"
petgraph = "0.6.0"
regex = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
sqlx = { version = "0.5", features = [ "runtime-async-std-native-tls", "any", "postgres", "sqlite" ] }

[dependencies.lalrpop-util]
version = "0.19.7"

[dependencies.pyo3]
version = "0.16.5"
# "extension-module" tells pyo3 we want to build an extension module (skips linking against libpython.so)
features = ["extension-module"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
