name: Create release and upload artifacts
on: [release]
#on:
#  push:
#    branches:
#      - 'main'
#      - 'releases/**'
env:
  CARGO_TERM_COLOR: always
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run tests
        run: |
          make test
      - name: Install musl
        run: sudo apt-get update && sudo apt-get install musl-tools
      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
          default: true
          override: true
      - name: Build
        run: cargo build --verbose --release --locked --target x86_64-unknown-linux-musl && cp target/x86_64-unknown-linux-musl/release/rdftab rdftab-x86_64-unknown-linux-musl
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: rdftab-x86_64-unknown-linux-musl
          path: rdftab-x86_64-unknown-linux-musl
