name: Valve Tests

on:
  pull_request:
    types:
      - ready_for_review
  push:
    branches:
      - '*'
env:
  CARGO_TERM_COLOR: always
jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install psycopg2
        run: |
          pip3 install -r requirements.txt
      - name: Run tests
        run: |
          # TODO: Add steps to set up a small postgres db, and then run `make test` instead
          # of just `make sqlite_test` below.
          make sqlite_test
