name: Valve Tests

on:
  pull_request:
    types:
      - ready_for_review
  push:
    branches:
      - '*'
env:
  CARGO_TERM_COLOR: always
jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Install postgresql server and client
        run: |
          sudo apt-get update
          sudo apt-get install postgresql postgresql-contrib postgresql-client sqlite3
      - name: Start the database server
        run: |
          sudo systemctl start postgresql.service
      - name: Create the valve_postgres database
        run: |
          sudo su - postgres -c "createuser runner"
          sudo su - postgres -c "createdb -O runner valve_postgres"
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install psycopg2
        run: |
          pip3 install -r requirements.txt
      - name: Run tests on both sqlite and on postgresql
        run: |
          make test
